[pytest]
testpaths = tests app/test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --cov=app --cov-report=term
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
